### ISSUE TITLE
能介绍下模型的类型吗？

### ISSUE THREAD

**Issue by 520jefferson** [360AILAB-NLP/360LayoutAnalysis#13]
非常感谢开源轻量级，简单易用的模型！有3个问题：
1.有这么多模型，能介绍下各自擅长哪个方向吗？比如publaynet-8n.pt、general6-8n.pt什么方向的？不太直观 ，另外（其他的是教材、论文、研报财报对吧）
2.另外，目前不能自适应吧，需要前面有个分类模型，对文档进行判定吧？ 
3.后续这些模型会合并吗？合并难度在哪里？如果担心参数量可以考虑yolo m和l级别的模型

![image](https://github.com/user-attachments/assets/5acc71ca-48f3-4b7a-a846-dda428a62c8d)

**Comment by SWHL** [comment]
我觉得如何能把对应的数据集给简单说一下，大家就能知道模型适用于哪些方向了

**Comment by yujunhuics** [comment]
1、请查看最新的readme
2、这个看你自己业务处理流程
3、目前不会合并，这个项目出于公益目的，暂时着力解决多场景问题；目前主打轻量，大参数量暂时不会开源，可以持续关注。

**Comment by 520jefferson** [comment]
> 1、请查看最新的readme 2、这个看你自己业务处理流程 3、目前不会合并，这个项目出于公益目的，暂时着力解决多场景问题；目前主打轻量，大参数量暂时不会开源，可以持续关注。

有没有考虑合并成一个模型呢？就是我很困惑我需要选哪个模型，如果文档分类不明的情况下，除非有个前置分类器或者用genneral模型了。 
另外试过layoutlmv3不？

**Comment by yujunhuics** [comment]
暂时不考虑，我们训完layoutlmv3，精度大差不差，速度太慢，不够轻量
