### ISSUE TITLE
有计划开源不同size的模型吗，比如8m 8l 8x等更大一些精度更高的模型

### ISSUE THREAD

**Issue by enymfc25173** [360AILAB-NLP/360LayoutAnalysis#5]

**Comment by yujunhuics** [comment]
后续如果有计划将在第一时间开放，感谢关注。

**Comment by enymfc25173** [comment]
![img_26](https://github.com/360AILAB-NLP/360LayoutAnalysis/assets/142864073/2653d727-5691-48a3-b607-3421af86d9c5)
另外请问下这种识别不全的情况有什么优化方案嘛，框出来了一句话的一半，还有一半漏了，以及看了还有不少漏块的情况

**Comment by liuhuanyong** [comment]
您好，我们的模型是基于研报训练的，您预测的是年报。存在泛化性的问题哈。
